export const RECOMENDATION = 'RECOMENDATION';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const FILTRED_RECIPES = 'FILTRED_RECIPES';
export const UPDATE_FAVORITE = 'UPDATE_FAVORITE';
export const DONE_RECIPES = 'DONE_RECIPES';
